nome = str(input('DIGITE SU NOME COMPLETO: '))
print(' >> ANALISANDO SEU NOME ....')
print(f'1. Seu nome em maiusculo é :{nome.upper()}')
print(f'2. Seu nome em minusculo é :{nome.lower()}')
print('3. Seu nome ao todo tem {} letras'.format(len(nome) - nome.count(' ')))
print('4. Seu primeiro nome tem {} letras' .format(nome.find(' ')))